//! Diesel DSL schema (generated by `diesel print-schema`)

table! {
    messages (id) {
        id -> Int4,
        phone_number -> Varchar,
        pdu -> Bytea,
        csms_data -> Nullable<Int4>,
    }
}

table! {
    recipients (id) {
        id -> Int4,
        phone_number -> Varchar,
        nick -> Varchar,
    }
}

